classification_dict = {
    "tak": "tak",
    "ani chybi": "tak",
    "bez dwoch zdan": "tak",
    "bezspornie": "tak",
    "bezsprzecznie": "tak",
    "jak najbardziej": "tak",
    "jakze by inaczej": "tak",
    "jasne": "tak",
    "ma sie rozumiec": "tak",
    "mowa": "tak",
    "na bank": "tak",
    "naturalnie": "tak",
    "nie inaczej": "tak",
    "nie ma dwoch zdan": "tak",
    "oczywiscie": "tak",
    "owszem": "tak",
    "pewnie": "tak",
    "racja": "tak",
    "rozumie sie": "tak",
    "rzecz jasna": "tak",
    "slusznie": "tak",
    "tak jest": "tak",
    "wiadomo": "tak",
    "wlasnie": "tak",
    "z cala pewnoscia": "tak",
    "ano": "tak",
    "dokladnie": "tak",
    "dokladnie tak": "tak",
    "istotnie": "tak",
    "no": "tak",
    "no tak": "tak",
    "rzeczywiscie": "tak",
    "w istocie": "tak",
    "w rzeczy samej": "tak",
    "zaiste": "tak",
    "no jasne": "tak",
    "prawda": "tak",
    "uhm": "tak",
    "yhm": "tak",
    "w samej rzeczy": "tak",
    "bezwzglednie": "tak",
    "no pewnie": "tak",
    "bez kwestii": "tak",
    "bez watpienia": "tak",
    "koniecznie": "tak",
    "obowiazkowo": "tak",
    "a jak": "tak",
    "a jakze": "tak",
    "jeszcze jak": "tak",
    "absolutnie": "tak",
    "nic dodac": "tak",
    "nic ujac": "tak",
    "otoz to": "tak",
    "zgadza sie": "tak",
    "zgoda": "tak",
    "dobra": "tak",
    "dobrze": "tak",
    "okay": "tak",
    "okej": "tak",
    "w porzadku": "tak",
    "zgadzam sie": "tak",
    "nom": "tak",
    "ok": "tak",
    "tak bardzo": "tak",
    "w ten sposob": "tak",
    "a i owszem": "tak",
    "na pewno": "tak",
    "pewno": "tak",
    "nie": "nie",
    "akurat": "nie",
    "ale gdzie tam": "nie",
    "ale skad": "nie",
    "ani troche": "nie",
    "bron Boze": "nie",
    "bynajmniej": "nie",
    "gdziez tam": "nie",
    "jeszcze czego": "nie",
    "nigdy w zyciu": "nie",
    "a skad": "nie",
    "skadze znowu": "nie",
    "gdzie tam": "nie",
    "pod zadnym pozorem": "nie",
    "za nic w swiecie": "nie",
    "za zadne skarby": "nie",
    "nie ma mowy": "nie",
    "nic takiego": "nie",
    "wykluczone": "nie",
    "skadze": "nie",
    "w zadnym razie": "nie",
    "wcale": "nie",
    "wcale nie": "nie",
    "absolutnie nie": "nie",
    "nigdy": "nie",
    "w zyciu": "nie",
    "zupelnie nie": "nie",
    "nie ma o czym mowic": "nie",
    "nie moze byc mowy": "nie",
    "nie wchodzi w rachube": "nie",
    "niestety": "nie",
    "niestety nie": "nie",
    "skad mam wiedziec": "nie wiem",
    "nie wiem": "nie wiem",
    "nie mam pojecia": "nie wiem",
    "nie mam zielonego pojecia": "nie wiem",
    "nie rozumiem": "nie wiem",
    "nie umiem": "nie wiem",
    "nie jestem pewien": "nie wiem",
    "nie orientuje sie": "nie wiem",
}
